package com.tuandev.fbsbarcode.integration.znack.signature;

public enum CryptoProErrorCode {
    CRYPTOPRO_MISSING,
    CRYPTCP_MISSING,
    CRYPTCP_LICENSE_INVALID,
    CERTMGR_MISSING,
    CADESCOM_MISSING,
    TOKEN_OR_CERTIFICATE_ABSENT,
    PRIVATE_KEY_UNAVAILABLE,
    CERTIFICATE_EXPIRED,
    CANCELLED,
    TIMEOUT,
    SIGNING_FAILED,
    INVALID_SIGNATURE_OUTPUT,
    DISCOVERY_FAILED
}
